name: Automated-Build

on:
  workflow_dispatch:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:v1.0
    steps:
    - name: Install dependencies
      run: |
        apk add build-base git zip
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow
    - name: Install ps2eth
      run: |
        git clone https://github.com/ps2dev/ps2eth.git
        cd ps2eth && make clean all install
    - name: Compile wLaunchELF
      run: |
        make TMANIP=1 
    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: wLaunchELF-${{ steps.slug.outputs.sha8 }}
        path: |
              *.ELF
    - name: Create release
      if: github.ref == 'refs/heads/master'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Latest automated build"
        files: |
               *.ELF


  build-funtuna-release:
    needs: [build]
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:v1.0
    steps:
    - name: Install dependencies
      run: |
        apk add build-base git zip
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow
    - name: Install ps2eth
      run: |
        git clone https://github.com/ps2dev/ps2eth.git
        cd ps2eth && make clean all install
    - name: Compile wLaunchELF
      run: |
        make TMANIP=2 FUNTUNA_RELEASE=1
    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: wLaunchELF-moron-${{ steps.slug.outputs.sha8 }}
        path: |
              *.ELF


  build-spanish:
    needs: [build]
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:v1.0
    steps:
    - name: Install dependencies
      run: |
        apk add build-base git zip
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow
    - name: Install ps2eth
      run: |
        git clone https://github.com/ps2dev/ps2eth.git
        cd ps2eth && make clean all install
    - name: Compile wLaunchELF
      run: |
        SCH=${GITHUB_SHA::7}
        echo "#include \"Lang/SPA.LNG\"">lang.h
        make TMANIP=1 
        mv BOOT.ELF BOOT-SPA.ELF
        mv BOOT-UNC.ELF BOOT-UNC-SPA.ELF
    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: wLaunchELF-spanish-${{ steps.slug.outputs.sha8 }}
        path: |
              *.ELF
    - name: Create release
      if: github.ref == 'refs/heads/master'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "español"
        title: "Ultima compilacion automatica"
        files: |
               *.ELF
               
  trigger-auto-update:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        repos: [israpps/FreeMcBoot-Installer, israpps/Funtuna-Fork]
    steps:
    - name: trigger israpps auto-update system
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
      uses: peter-evans/repository-dispatch@v1
      with:
          token: ${{ secrets.IUS }}
          repository: ${{ secrets.IUS }}
          event-type: Component_update
          client-payload: '{"sha": "${{ github.sha }}"}'